version: '3.4'

services:
  pipelinecovidsaudebrhitechnology:
    image: pipelinecovidsaudebrhitechnology
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 9200:9200
      - 9300:9300
